### ISSUE TITLE
Building an app package

### ISSUE THREAD

**Issue by Lucki** [akdor1154/WinNetSty#1]
Hi,
this is exactly what I was looking for, but your app link gives a 404.

So I've tried to build it myself, but I'm stuck currently.
Visual Studio compiles the app fine, but windows doesn't want to start the resulting .exe. Windows wants it in an app package. But here the problem starts, because when I tell Visual Studio to create an app package out of this application Visual Studio instantly crashes.
I don't think this is related to your program, but I don't know how to proceed here - I haven't done anything with windows apps before and I'm not familiar with Visual Studio.

Is there another source for the pre-compiled app or can I somehow start the compiled .exe without making an app package out of it?

I've already posted this [in the forum of Networktablet](https://forums.bitfire.at/post/7699) but saw your last online activity and decided to write it here too.

**Comment by akdor1154** [comment]
Hey! Looks like MS have removed it from the store for unknown reasons. I'll try and get it back up tonight, thanks for the heads up.
wrt Visual Studio, I really wouldn't know where to start, sorry. I built it with VS 2015 Community if that helps. I will probably upgrade it to VS 2017 as part of resubmitting it to MS, as that's what I have on my machine currently.
As for launching it outside of an app package, all I can think of are the Developer options in Win 10 settings, controlling whether you can launched signed, sideloaded, or all apps. Maybe try changing this to all?

Jarrad

**Comment by Lucki** [comment]
I finally got this app package.
But the app closes itself after a few seconds of a visible colored background. This happens with the latest commit and with 0.1.
I think I have to wait until the app is back in store to know if it's problem caused by my build.

**Comment by akdor1154** [comment]
Hey, finally got around to looking at this (sorry). I have it running on my PC with a fresh install of Windows 10 and VS 2017, no mucking about was required beyond putting my machine into Developer mode and rebooting. VS 2015 should work as well. Is there anything interesting in the logs that show when you try to launch in VS?

The store removed it due to lack of interest. I need to re-submit it but there is a complication in that I managed to lose my store signing key when reformatting this PC (d'oh!). Not sure how long that will take.

**Comment by Lucki** [comment]
I'm sorry, but I can't debug this. My Surface 3 has not enough free space to install Visual Studio and the remote debuging of Visual Studio doesn't work. I've tried to start the app with the command line to see if there's any output but that also failed. There are no errors at the build process.
I'm a bit disappointed and don't want to spend much more time in this.
This whole UWP seems nice when everything works and is available in the store. But anything other is highly inpractical and frustrating.
I'm sorry, I can't build and use your program. Please consider releasing it outside the Microsoft Store (heads up to 

> The store removed it due to lack of interest.

) as mentioned in #2 .

**Comment by Lucki** [comment]
Thanks for getting it back up in the store.
That version works, so i've bought it.

This issue isn't really solved by that, but it looks like an problem on my side so I'll close this issue.
